### ISSUE TITLE
XML Contains errors

### ISSUE THREAD

**Issue by xlwang233** [simonscheider/mapmatching#3]
Hi Simon!
I was trying to use the method as the ArcGIS tool. I did everything step by step just as told. Having successfully installed GDAL-2.2.3-win32 and networkx-2.1 and also the toolbox as well as those two .xml files. But when I tried to open it in ArcCatalog it failed and the "Description" of it says **the item's XML contains errors**.
My ArcGIS version is 10.5. I am now really frustrated by this. Could you review my problem and offer some advice? I would be utterly grateful!

**Comment by simonscheider** [comment]
I have tested the version including the ArcGIS toolbox right now with ArcGIS 10.3. Everything should work well now (corrected the networkx 2.0 errors). I have not tested with ArcGIS 10.5, but they should be backwards compatible. If there remains to be an issue with the toolbox xml, then I would just use the tool not in a toolbox, but simply by calling this inside the arcgis python window (assuming you have reinstalled all modules including mapmatcher correctly):

import mapmatcher
opt = mapmatcher.mapMatch('testTrack.shp', 'testSegments.shp', 25, 10, 50)    
mapmatcher.exportPath(opt, 'testTrack.shp')
